<a href="https://colab.research.google.com/github/Sourabh-verma-01/Gen-AI/blob/main/numpy_assignemnt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment Numpy

Q 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
import numpy as np

In [ ]:
#Ans 1. -
arr =np.array([0,1,2,3,4,5])
print(arr)
print(arr.dtype)

[0 1 2 3 4 5]
int32


Q 2. Given a NumPy array 'arr', check if its data type is float64.
     Arr = np.array([1.5, 2.6, 3.7])


In [ ]:
 Arr = np.array([1.5, 2.6, 3.7])

In [ ]:
# Ans 2 -
if (arr.dtype) == np.float64:
    print ('True')

else:
    print ("false")

false


Q 3. Create a Numpy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
# Ans -

arr = np.array([1+2j, 3+4j, 5+6j], dtype= np.complex128)
print(arr.dtype)
print(arr)


complex128
[1.+2.j 3.+4.j 5.+6.j]


Q 4. Convert an existing Numpy array 'arr' of integers to float32 data type.

In [ ]:
# Ans -

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)


[1. 2. 3. 4. 5.]
float32


Q 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
# Ans -
import numpy as np

arr = np.array([1.1239, 2.987, 3.1415], dtype=np.float64)
arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)

[1.1239 2.987  3.1415]
float32


Q 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [ ]:
#Ans -

arr = np.array([2,3,4,5,6])
print(arr)
print(arr.size)
print(arr.shape)
print(arr.dtype)

[2 3 4 5 6]
5
(5,)
int32


Q 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [ ]:
# Ans -

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(list[arr])
print(arr.ndim)


list[array([[1, 2, 3],
       [4, 5, 6]])]
2


Q 8 . Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [ ]:
# Ans -

def item_size_info(arr):

    arr = np.array([[2,3,4,5], [8,9,6,7]])

    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size
print(item_size_info(arr))

(4, 32)


Q 9 -  Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
# Ans -

import numpy as np

def array_strides(arr) :

    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], )
print(array_strides(arr))  # Output: (12, 4) for int32 type


(12, 4)


Q 10 - Design a function shape_stride_relationship that takes a Numpy array as input and returns the shape and strides of the array

In [ ]:
# Ans -
import numpy as np

def shape_stride_relationship(arr):

    return  arr.shape,arr.strides


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(shape_stride_relationship(arr))


((2, 3), (12, 4))


Q 11 - . Create a function create_zeros_array that takes an integer 'n' as input and returns a NumPy array of zeros with 'n' olements.

In [ ]:
# Ans -
n =5
def create_zeros_array(n):
    return np.zeros(n)
print(create_zeros_array(n))

[0. 0. 0. 0. 0.]


Q 12 -  Write a function create_ones_matrix that takes integers 'rows' and 'cols' as inputs and generates a 2D NumPy array filled with ones of size 'rows x cols.

In [ ]:
#Ans -

def create_ones_matrix(rows, cols):

     return np.ones((rows, cols))
rows, cols = 3, 4
print(create_ones_matrix(rows, cols))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Q 13 - . Write a function 'generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from 'start', ending at stop (exclusive), and with the specified step.

In [ ]:
# Ans -

def generate_range_array (start, stop, step):

    return np.arange (start, stop, step)


arr = generate_range_array(0, 10, 2)
print(arr)


[0 2 4 6 8]


Q 14 - Design a function generate_linear_space that takes two floats 'start', 'stop', and an integer 'num' as arguments and generates a NumPy array with num equally spaced valuer between 'start' and 'stop' (inclusive).

In [ ]:
# Ans -

def generate_linear_space(start: float, stop: float, num: int):

    return np.linspace(start, stop, num)

array = generate_linear_space(0, 10, 5)
print(array)


[ 0.   2.5  5.   7.5 10. ]


Q 15 -  Create a function 'create_identity_matrix' that takes an integer 'n' as input and generates a square identity matrix of size n x n' using 'numpy.eye.

In [ ]:
# Ans -

def create_identity_matrix(n):
    return np.eye(n)
print(create_identity_matrix(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Q 16 - Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
# Ans -
lis = [2,3,4,5,6]
arr= np.array(lis)

print(type(lis))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


Q. 17 - Create a NumPy array and demonstrate the use of 'numpy.view' to create a new array object with the same data

In [ ]:
# Ans -
arr = np.array([1, 2, 3, 4, 5])

a_view = arr.view()

a_view[0] = 99
print("Original Array:", arr)
print("Viewed Array:", arr_view)


Original Array: [99  2  3  4  5]
Viewed Array: [99  2  3  4  5]


Q. 18 - Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
# Ans -
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

def concat_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)


print(concat_arrays(a, b, axis=0))
print(concat_arrays(a, b, axis=1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Q.19 - Create two NumPy arrays with different shapes and concatenate them horizontally using "numpy. concatenate.

In [ ]:
# Ans -

a = np.array ([[2,3] ,[8,9]])
b = np.array ([[4,5],[6,7]])

np.concatenate((a,b),axis =1)

array([[2, 3, 4, 5],
       [8, 9, 6, 7]])

Q. 20 - Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
# Ans -

lis = (5,6,7,8,9)

def ver (lis):
    return np.vstack(lis)

print(ver(lis))

[[5]
 [6]
 [7]
 [8]
 [9]]


Q. 21 - . Write a Python function using NumPy to create an array of integers within a specified range (Inclusive) with a given step size.

In [ ]:
# Ans -

def arr(start,end,step):
    return np.arange(start, end + 1, step)

print(arr(1, 10, 2))

[1 3 5 7 9]


Q.22 - . Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [ ]:
# Ans -
def generate_linspace():
    return np.linspace(0, 1, 10)
print(generate_linspace())


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Q. 23 - Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [ ]:
# Ans -

import numpy as np

def generate_logspace():
    return np.logspace(0, 3, 5)
print(generate_logspace())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


Q. 24 - Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [ ]:
# Ans -

import pandas as pd

def create_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    return pd.DataFrame(data, columns=['A', 'B', 'C'])


df = create_dataframe()
print(df)


    A   B   C
0  92  73  77
1  85  53  20
2  21  88  58
3  12  75  76
4  46  77  11


Q. 25- Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
# Ans -
def replace_negatives_with_zero(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df
data = {'A': [1, -2, 3, -4, 5], 'B': [-1, 2, -3, 4, -5]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negatives_with_zero(df, 'A')

print("\nModified DataFrame:")
print(df)


Original DataFrame:
   A  B
0  1 -1
1 -2  2
2  3 -3
3 -4  4
4  5 -5

Modified DataFrame:
   A  B
0  1 -1
1  0  2
2  3 -3
3  0  4
4  5 -5


Q 26 - Access the 3rd element from the given NumPy array.

In [ ]:
# Ans -
arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


Q. 27 - . Retrieve the element at Index (1, 2) from the 2D NumPy array.

       arr_2d np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
# Ans -

import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


Q. 28 - Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr= np.array([3, 8, 2, 18, 5, 7])

In [ ]:
# Ans -
arr = np.array([3, 8, 2, 18, 5, 7])
filtered_elements = arr[arr > 5]
print("Elements greater than 5:", filtered_elements)


Elements greater than 5: [ 8 18  7]


Q. 29 - Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Ans -

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_elements = arr[2:6]

print("Extracted elements:", sliced_elements)


Extracted elements: [3 4 5 6]


Q. 30 -
Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.
arr 2d np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])


In [ ]:
# Ans -

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:")
print(sub_array)


Extracted sub-array:
[[2 3]
 [5 6]]


Q. 31 -
       Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.


In [ ]:
# Ans -
def extract_elements_by_indices(arr_2d, indices):
    return arr_2d[indices[:, 0], indices[:, 1]]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]])

extracted_elements = extract_elements_by_indices(arr_2d, indices)

print("Extracted elements:", extracted_elements)


Extracted elements: [2 6 7]


Q. 32 -
Create a NumPy function that filters elements greater than a threshold from a given ID array using boolean indexing.


In [ ]:
# Ans -
import numpy as np

def filter_elements_by_threshold(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 5, 10, 3, 7, 12, 6])
threshold = 6

filtered_elements = filter_elements_by_threshold(arr, threshold)
print("Filtered elements:", filtered_elements)


Filtered elements: [10  7 12]


Q. 33 -
Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [ ]:
# Ans -
row = np.array([0, 1, 2])
col = np.array([1, 0, 1])
depth = np.array([0, 1, 0])

def extract_elements_from_3d_array(arr_3d, row, col, depth):
    return arr_3d[row, col, depth]

arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]],
                   [[9, 10], [11, 12]]])

extracted_elements = extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices)

print("Extracted elements:", extracted_elements)


Extracted elements: [ 3  6 11]


Q. 34 -
Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.


In [ ]:
# Ans -
arr = np.array([1, 5, 10, 3, 7, 12, 6])

def filter_by_conditions(arr, cond1, cond2):
    return arr[cond1 & cond2]

filtered_elements = filter_by_conditions(arr, arr > 3, arr % 2 == 0)

print("Filtered elements:", filtered_elements)


Filtered elements: [10 12  6]


Q. 35 - Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.


In [ ]:
# Ans -

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

def extract_elements(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

extracted_elements = extract_elements(arr_2d, row_indices, col_indices)

print("Extracted elements:", extracted_elements)


Extracted elements: [2 6 7]


Q. 36 -
      Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
# Ans -

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result = arr + 5

print("Array after adding 5 to each element:")
print(result)



Array after adding 5 to each element:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


Q. 37 -
Consider two arrays arrl of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arrl using NumPy broadcasting.

In [ ]:
# ans -

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])

arr1_reshaped = arr1.T  # Shape (3, 1)

result = arr2 * arr1_reshaped

print("Result after multiplication:")
print(result)


Result after multiplication:
[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


Q. 38 - Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [ ]:
# Ans -
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])


result = arr2 + arr1[:, :3]

print(result)


[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


Q. 39 - Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [ ]:
# Ans -
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


Q. 40 - . Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility

In [ ]:
# Ans -
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

arr2_reshaped = arr2[:, :, np.newaxis]
result = arr1 * arr2_reshaped

print("Result after multiplication:")
print(result)


Result after multiplication:
[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


Q. 41 - Calculate column-wise mean for the given array:

arr np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
# Ans -

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_mean = np.mean(arr, axis=0)

print("Column-wise mean:", column_mean)


Column-wise mean: [2.5 3.5 4.5]


Q . 42 - Find maximum value in each row of the given array:

arr np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
# Ans -

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
row_max = np.max(arr, axis=1)

print("Row-wise maximum values:", row_max)



Row-wise maximum values: [3 6]


Q. 43 - For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])


In [ ]:
#Ans -
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
column_max_indices = np.argmax(arr, axis=0)

print("Indices of maximum values in each column:", column_max_indices)

Indices of maximum values in each column: [1 1 1]


Q 44 -
For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
#Ans -
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

def moving_sum(arr, window_size=2):
    result = np.array([np.convolve(row, np.ones(window_size, dtype=int), mode='valid') for row in arr])
    return result

result = moving_sum(arr, window_size=2)

print( result)



[[ 3  5]
 [ 9 11]]


Q.45 - . In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])


In [ ]:
# Ans  -
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

column_even_check = np.all(arr % 2 == 0, axis=0)

print( column_even_check)


[False False False]


Q. 46 - Given a NumPy array arr, reshape it into a matrix of dimensions 'm' rows and 'n' columns. Return the reshaped matrix.

        original_array = np.array([1, 2, 3, 4, 5, 6])


In [ ]:
# Ans -

original_array = np.array([1, 2, 3, 4, 5, 6])

def reshape_array(arr, m, n):
    return arr.reshape(m, n)

reshaped_matrix = reshape_array(original_array, 2, 3)

print("Reshaped matrix:\n", reshaped_matrix)



Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


Q. 47 - Create a function that takes a matrix as input and returns the flattened array.

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
# Ans -

input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

def flatten_matrix(matrix):
    return matrix.flatten()

flattened_array = flatten_matrix(input_matrix)

print("Flattened array:", flattened_array)


Flattened array: [1 2 3 4 5 6]


Q. 48 - . Write a function that concatenates two given arrays along a specified axis.

array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])


In [ ]:
# Ans -
array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

def concat(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

result_axis1 = concat(array1, array2, axis=1)
print("Concatenated along axis 1:\n", result_axis1)

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


Q. 49 -Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:
# Ans -

original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

def split_array(arr, sections, axis=0):
    return np.array_split(arr, sections, axis=axis)

split_rows = split_array(original_array, 3, axis=0)
print( split_rows)

split_columns = split_array(original_array, 3, axis=1)
print( split_columns)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


Q. 50 -
Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]


In [ ]:
# Ans -
import numpy as np

def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):

    for idx, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, idx, value)

    for idx in sorted(indices_to_delete, reverse=True):
        original_array = np.delete(original_array, idx)

    return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)


[ 1 10 11  4  5]


Q. 51 -  
Create a NumPy array 'arrl with random integers and another array arr2` with integers from 1 to 10. Perform element-wise addition between 'arrl' and 'arr2".

In [ ]:
# Ans -
arr1 = np.random.randint(1, 20, size=5)
arr2 = np.arange(1, 11)[:5]

result = arr1 + arr2

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"Result of addition: {result}")


arr1: [17  4  6 19 19]
arr2: [1 2 3 4 5]
Result of addition: [18  6  9 23 24]


Q. 52 -
Generate a NumPy array 'arrl with sequential integers from 10 to 1 and another array 'arr2' with integers from 1 to 10. Subtract arr2` from `arri element-wise.

In [ ]:
# Ans -

arr1 = np.arange(10, 0, -1)

arr2 = np.arange(1, 11)

result = arr2 - arr1

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"Result of subtraction: {result}")


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of subtraction: [-9 -7 -5 -3 -1  1  3  5  7  9]


Q. 53 -
Create a NumPy array 'arrl with random integers and another array 'arr2' with integers from 1 to 5. Perform element-wise multiplication between 'arrl' and 'arr2.

In [ ]:
#Ans -

arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)

result = arr1 * arr2

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"Result of multiplication: {result}")


arr1: [1 1 2 9 7]
arr2: [1 2 3 4 5]
Result of multiplication: [ 1  2  6 36 35]


Q. 54 - Generate a NumPy array'arrl with even integers from 2 to 10 and another array 'arr2` with integers from 1 to 5. Perform element-wise division of `arrl by `arr2.

In [ ]:
# Ans -

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

result = arr1 / arr2

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"Result of division: {result}")


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result of division: [2. 2. 2. 2. 2.]


Q. 55 -
 Create a NumPy array arrl with integers from 1 to 5 and another array 'arr2 with the same numbers reversed. Calculate the exponentiation of arrl' raised to the power of 'arr2 element-wise.

In [ ]:
# Ans -
arr1 = np.arange(1, 6)

arr2 = arr1[::-1]

result = arr1 ** arr2

print(f"arr1: {arr1}")
print(f"arr2: {arr2}")
print(f"Result of exponentiation: {result}")


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result of exponentiation: [ 1 16 27 16  5]


Q. 56 -
 Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [ ]:
# Ans -

def count_substring(arr, substring):
    return np.sum(np.char.find(arr, substring) != -1)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

count = count_substring(arr, substring)
print(f"Occurrences of '{substring}': {count}")


Occurrences of 'hello': 3


Q. 57 -
Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAl', 'GPT'])

In [ ]:
# Ans -

import numpy as np
import re

def extract_uppercase(arr):
    return np.vectorize(lambda x: ''.join(re.findall(r'[A-Z]', x)))(arr)

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

uppercase_chars = extract_uppercase(arr)
print(f"Uppercase characters: {uppercase_chars}")



Uppercase characters: ['H' 'W' 'OAI' 'GPT']


Q. 58 -  
 Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
# Ans -

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)


arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'

modified_arr = replace_substring(arr, old_substring, new_substring)
print(f"Modified array: {modified_arr}")


Modified array: ['orange' 'banana' 'grape' 'pineorange']


Q. 59 -
Write a function that concatenates strings in a NumPy array element-wise.

arr1= np.array(['Hello', 'World'])

arr2= np.array(['Open', 'AI'])


In [ ]:
# Ans -
def concatenate_strings(arr1, arr2):
    return np.core.defchararray.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

concatenated_arr = concatenate_strings(arr1, arr2)
print(f"Concatenated array: {concatenated_arr}")


Concatenated array: ['HelloOpen' 'WorldAI']


Q 60 -
 Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

arr np.array(['apple', 'banana', 'grape', 'pineapple'])



In [ ]:
#Ans -
def longest_string_length(arr):
    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

max_length = longest_string_length(arr)
print(f"Length of the longest string: {max_length}")


Length of the longest string: 9


Q. 61 -
Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [ ]:
# Ans -
dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print(f"Mean: {mean}, Median: {median}, Variance: {variance}, Standard Deviation: {std_dev}")


Mean: 492.47, Median: 488.0, Variance: 77485.7691, Standard Deviation: 278.36265751713177


Q. 62-
Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [ ]:
# Ans -
data = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f"25th percentile: {percentile_25}, 75th percentile: {percentile_75}")


25th percentile: 28.0, 75th percentile: 75.75


Q. 63 -
 Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's 'corrcoef function.

In [ ]:
# Ans -


arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])


correlation_matrix = np.corrcoef(arr1, arr2)

correlation_coefficient = correlation_matrix[0, 1]

print(f"Correlation coefficient: {correlation_coefficient}")


Correlation coefficient: -0.9999999999999999


Q. 64 -
Create two matrices and perform matrix multiplication using NumPy's 'dot' function.

In [ ]:
# Ans -

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)

print(result)


[[19 22]
 [43 50]]


Q. 65 -
Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.



In [ ]:
# Ans -

data = np.random.randint(10, 1001, size=50)


percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)
quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)

print(percentile_10)
print(percentile_50)
print(percentile_90)
print(quartile_1)
print(quartile_3)


132.4
524.5
896.1
340.5
769.0


Q. 66 -
Create a NumPy array of integers and find the index of a specific element.

In [ ]:
# Ans -
arr = np.array([10, 20, 30, 40, 50])

index = np.where(arr == 30)[0][0]

print(index)


2


Q. 67 -
Generate a random NumPy array and sort it in ascending order.


In [ ]:
#Ans -
arr = np.random.randint(1, 101, size=10)

sorted_arr = np.sort(arr)

print(f"Original array: {arr}")
print(f"Sorted array: {sorted_arr}")


Original array: [11 21 18 69 31 37 96 36 45 26]
Sorted array: [11 18 21 26 31 36 37 45 69 96]


Q. 68-
Filter elements >20 in the given NumPy array.

arr = np.array ([12, 25, 6, 42, 8, 30])


In [ ]:
# Ans -
arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print(f"Elements greater than 20: {filtered_arr}")


Elements greater than 20: [25 42 30]


Q.69 -
Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])


In [ ]:
# Ans -
arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]

print(f" divisible by 3: {filtered_arr}")


 divisible by 3: [12 15]


Q. 70 -
Filter elements which are 2 20 and $ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])

In [ ]:
# Ans -
arr = np.array([10, 20, 30, 40, 50])

filtered_arr = arr[(arr == 20) | (arr == 40)]

print(f"Elements that are 20 or 40: {filtered_arr}")


Elements that are 20 or 40: [20 40]


Q. 71 -
 For the given NumPy array, check its byte order using the 'dtype` attribute byteorder.

arr= np.array([1, 2, 3])


In [ ]:
# Ans -
arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print(f"Byte order: {byte_order}")


Byte order: =


Q. 72 -
For the given NumPy array, perform byte swapping in place using byteswap()".

arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
#Ans -

arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(inplace=True)

print(f"Byte-swapped array: {arr}")


Byte-swapped array: [16777216 33554432 50331648]


Q.73 -
For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().

arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
# Ans -
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()

print(f"Original array: {arr}")
print(f"Byte-swapped array: {swapped_arr}")


Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


Q. 74 -
    For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder().

    arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
# Ans -
import sys
arr = np.array([1, 2, 3], dtype=np.int32)


if sys.byteorder == 'little':

    swapped_arr = arr.newbyteorder('>')
else:

    swapped_arr = arr

print(arr)
print(swapped_arr)


[1 2 3]
[16777216 33554432 50331648]


Q. 75 -
For the given NumPy array, check if byte swapping is necessary for the current system using 'dtype" attribute byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)


In [ ]:
# Ans -
import sys

arr = np.array([1, 2, 3], dtype=np.int32)
array_byte_order = arr.dtype.byteorder

system_byte_order = sys.byteorder

if array_byte_order != system_byte_order:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")

print(f"Array byte order: {array_byte_order}")
print(f"System byte order: {system_byte_order}")


Byte swapping is necessary.
Array byte order: =
System byte order: little


Q. 76 -
Create a NumPy array arrl with values from 1 to 10. Create a copy of arrl named 'copy_arr and modify an element in 'copy_arr. Check if modifying copy_arr affects `arrl.

In [ ]:
# Ans -

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

copy_arr = arr1.copy()

copy_arr[0] = 100

print("Original array (arr1):", arr1)
print("Modified copy (copy_arr):", copy_arr)


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy (copy_arr): [100   2   3   4   5   6   7   8   9  10]


Q. 77 -
Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice 'view_slice from the matrix. Modify an element in 'view_slice and observe if it changes the original matrix'.


In [ ]:
#Ans -
matrix = np.random.randint(1, 10, size=(3, 3))

view_slice = matrix[1:, 1:]

view_slice[0, 0] = 100

print("Original matrix:")
print(matrix)

print("\nModified view_slice:")
print(view_slice)


Original matrix:
[[  6   2   7]
 [  3 100   3]
 [  1   6   4]]

Modified view_slice:
[[100   3]
 [  6   4]]


Q. 78 -
Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b'from array_a and broadcast the addition of 5 to view_b. Check if it alters the original 'array_a.

In [ ]:
# Ans -

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:, 1:]

view_b += 5

print("Original array_a:")
print(array_a)

print("\nModified view_b:")
print(view_b)


Original array_a:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]

Modified view_b:
[[10 11]
 [13 14]
 [16 17]]


Q. 79 -
Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in 'reshaped_view and check if it reflects changes in the original'orig_array.

In [ ]:
# Ans  -
import numpy as np

# Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[1, 1] = 100

# Check if it reflects changes in the original orig_array
print("Original orig_array:")
print(orig_array)

print("\nModified reshaped_view:")
print(reshaped_view)


Original orig_array:
[[  1   2   3 100]
 [  5   6   7   8]]

Modified reshaped_view:
[[  1   2]
 [  3 100]
 [  5   6]
 [  7   8]]


Q 80 -
Create a NumPy array 'data' of shape (3, 4) with random integers. Extract a copy 'data_copy of elements greater than 5. Modify an element in 'data_copy' and verify if it affects the original 'data'

In [ ]:
# Ans -
data = np.random.randint(1, 11, size=(3, 4))

data_copy = data[data > 5].copy()

data_copy[0] = 100

print("Original data:")
print(data)

print("\nModified data_copy:")
print(data_copy)


Original data:
[[ 8  5  3  7]
 [ 2  8  2  7]
 [ 4 10  6  7]]

Modified data_copy:
[100   7   8   7  10   6   7]


Q 81 -
Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [ ]:
# Ans -

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

addition_result = A + B

subtraction_result = A - B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition of A and B:")
print(addition_result)

print("\nSubtraction of A and B:")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition of A and B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of A and B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


Q. 82 -
Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.

In [ ]:
# Ans -

C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

result = np.dot(C, D)

print("Matrix C (3x2):")
print(C)

print("\nMatrix D (2x4):")
print(D)

print("\nMatrix multiplication result (C * D):")
print(result)


Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]

Matrix D (2x4):
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix multiplication result (C * D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


Q 83 -
Create a matrix E and find its transpose.

In [ ]:
#Ans -

E = np.array([[1, 2], [3, 4], [5, 6]])

E_transpose = E.T

print("Matrix E:")
print(E)

print("\nTranspose of matrix E:")
print(E_transpose)


Matrix E:
[[1 2]
 [3 4]
 [5 6]]

Transpose of matrix E:
[[1 3 5]
 [2 4 6]]


Q 84 -
Generate a square matrix F and compute its determinant.

In [ ]:
# Ans -
F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

determinant_F = np.linalg.det(F)

print("Matrix F:")
print(F)

print("\nDeterminant of matrix F:", determinant_F)


Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of matrix F: 0.0


Q. 85 -
Create a square matrix 'G' and find its inverse

In [ ]:
# Ans -

G = np.array([[4, 7], [2, 6]])

G_inverse = np.linalg.inv(G)

print("Matrix G:")
print(G)

print("\nInverse of matrix G:")
print(G_inverse)


Matrix G:
[[4 7]
 [2 6]]

Inverse of matrix G:
[[ 0.6 -0.7]
 [-0.2  0.4]]
